apiVersion: apps/v1
kind: Deployment
metadata:
  name: appweb
spec:
  replicas: 6
  selector:
    matchLabels:
      app: appweb
  template:
    metadata:
      labels:
        app: appweb
    spec:
      containers:
      - name: appweb
        image: deivisson/conversao-temperatura:v1
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: appweb
spec:
  selector:
   app: appweb
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
